st.markdown(
    """
    <style>
    div.stDownloadButton > button {
        background-color: #1E88E5;
        color: white;
        font-weight: 600;
        border-radius: 12px;
        padding: 12px 24px;
        transition: background-color 0.3s ease;
    }
    div.stDownloadButton > button:hover {
        background-color: #1565c0;
    }
    </style>
    """,
    unsafe_allow_html=True
)
