[theme]
primaryColor = "#1E88E5"
backgroundColor = "#F7F9FB"
secondaryBackgroundColor = "#E3F2FD"
textColor = "#212121"
font = "sans serif"

[layout]
wideMode = true

[client]
toolbarMode = "minimal"
